services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: url_shortener
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: url_shortener
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_RETRY_INTERVAL: 5000  # Интервал между попытками подключения (мс)
      DB_RETRY_LIMIT: 10       # Максимальное количество попыток
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    restart: on-failure  # Перезапускать при ошибках

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge